stages:
  prepare:
    cmd: python src/tweets_extraction.py
    deps:
      - src/tweets_extraction.py
    outs:
      - data/raw_tweets.json:
          cache: false
          persist: true
  process:
    cmd: python src/tweets_cleaning.py
    deps:
      - data/raw_tweets.json
      - src/tweets_cleaning.py
    outs:
      - data/cleaned_tweets.csv:
          cache: false
          persist: true
  classification:
    cmd: python src/tweets_classification.py
    deps:
      - data/cleaned_tweets.csv
      - src/tweets_classification.py
    outs:
      - data/classified_tweets.csv:
          cache: false
          persist: true
